apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-w10e1
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service-container
        image: acrweek10shivanisatav.azurecr.io/customer_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        env:
        - name: POSTGRES_HOST
          value: customer-db-service-w10e1
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w10e1
              key: CUSTOMERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-config-w10e1
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-config-w10e1
              key: POSTGRES_PASSWORD
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w10e1
              key: ORDER_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-w10e1
  labels:
    app: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: LoadBalancer
