apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-w10e1
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: acrweek10shivanisatav.azurecr.io/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w10e1
              key: PRODUCT_SERVICE_URL
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w10e1
              key: ORDER_SERVICE_URL
        - name: CUSTOMER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w10e1
              key: CUSTOMER_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-w10e1
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80      # Expose on port 80 for browser access
      targetPort: 3000
  type: LoadBalancer
