# Trigger testing branch
name: Backend CI - Test and Push to ACR

on:
  push:
    branches:
      - testing

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and test Customer Service
        run: |
          cd backend/customer_service
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-service:latest .
          # run unit tests
          docker run --rm ${{ secrets.ACR_NAME }}.azurecr.io/customer-service:latest pytest

      - name: Build and test Order Service
        run: |
          cd backend/order_service
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/order-service:latest .
          docker run --rm ${{ secrets.ACR_NAME }}.azurecr.io/order-service:latest pytest

      - name: Build and test Product Service
        run: |
          cd backend/product_service
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/product-service:latest .
          docker run --rm ${{ secrets.ACR_NAME }}.azurecr.io/product-service:latest pytest
      
      - name: Build and test Frontend 
        run: |
          cd backend/product_service
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest .
          docker run --rm ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest pytest

      - name: Push backend images to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-service:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/order-service:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/product-service:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest
